### PR TITLE
added javadoc to subsystems

### PR DESCRIPTION
**Pull request by 222lore**

### CODE REVIEW

**Comment by LordSquishers** [comment]
nice

**Comment by 222lore** [comment]
> nice

nice

**Comment by LordSquishers** [comment]
> > nice
> 
> nice

nice

**Comment by 222lore** [comment]
> > > nice
> > 
> > 
> > nice
> 
> nice

nice

**Comment by LordSquishers** [comment]
> > > > nice
> > > 
> > > 
> > > nice
> > 
> > 
> > nice
> 
> nice

nice

**Comment by 222lore** [comment]
> > > > > nice
> > > > 
> > > > 
> > > > nice
> > > 
> > > 
> > > nice
> > 
> > 
> > nice
> 
> nice

nice

**Comment by emreg22** [comment]
> > > > > > nice
> > > > > 
> > > > > 
> > > > > nice
> > > > 
> > > > 
> > > > nice
> > > 
> > > 
> > > nice
> > 
> > 
> > nice
> 
> nice

nice

**Pull request merged**
